### ISSUE TITLE
[French version] - Cardiolody Unit in english

### ISSUE THREAD

**Issue by Damn3d** [sleepy068/ProjectHospital_Oncology#2]
Hi sleepy :)

Not a big issues but i like to report when i saw a problem (even little).

The unit seems to work perfectly in french, except the Cardiology Unit (only for your Onclogy services, no problem in main game services).

[https://i.imgur.com/88qPxdK.jpg](https://i.imgur.com/88qPxdK.jpg)

Voilà :)

**Comment by sleepy068** [comment]
Hi Damn3d, no worries at all mate, unfortunately I don't speak any language other than English and rely on translators to translate into other languages for me. This is an example of when I've updated my mod and the translator has not been able to provide an updated language version or may no longer support this mod via translation (this mod is very text heavy so it is a lot of work, it is understandable if people just don't have the time). I can fix this exact issue with Google Translate but for the bulk of the text it just isn't reliable when I cannot be sure what I am saying in French. Hope that helps.

**Comment by Damn3d** [comment]
Can you please give me the missing lines on my screenshot ? I will do it here for you :)
If need more jobs, i will contact you to do it directly on the file ;)

**Comment by sleepy068** [comment]
Hi Damn3d, it is a bit more complicated sorry, my localisation code has line breaks to tell the translator what was added in the latest version across all locale documents.  If you download the mod and dig through the code, it'll be clear what is missing in the two versions but I just don't have the time to maintain other languages myself sorry.
For example. The French translation is already missing 31 lines of text from the latest English version in just the Diagnosis xml file.

If you'd like to help, it is always welcome, I've provided a tutorial here and can accept the files whatever way works (I have a discord too).
I post to this thread updates to existing localisation.
https://steamcommunity.com/workshop/filedetails/discussion/1938136264/2632850242350620154/

For you however, I will translate the missing lines myself and get them into the next update (I will use the games french locale to ensure it is correct)(MacNabb that made the Gynecology mod is a friend of mine and is french so that might help).

**Comment by Damn3d** [comment]
Sure, i will help you and make this (well, i will try anyway) !
But for the Cardiology problem, it's not an issue with the translation i think.
Just compare ModStringTableEnBuildingMode & ModStringTableFrBuildingMode and they are totally the same !

Maybe, because it's a maingame room, if you not add it in your mods, the game use the default in main language or something like that ?

I've make a search on the entire folder with term "Cardiology" and find absolutly nothing ;)

**Comment by Damn3d** [comment]
Can you give me your Discord ID please ? :)

I'm on the translation :D

**Comment by sleepy068** [comment]
Hi Damn3d, https://discord.gg/Z42Fdrm

**Comment by Damn3d** [comment]
Hi :)

I'm on it and i have reported some issue (or question) on your Discord. Look asap :)

But the mod is almost translated :)
